### ISSUE TITLE
npx prisma db push is failing

### ISSUE THREAD

**Issue by being-dev-entity** [daniserrano7/jira-clone#1]
I am getting this below error , can you please update read me file with each step. for setting db as well.

>npx prisma db push
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
Environment variables loaded from .env
Prisma schema loaded from src\infrastructure\db\schema.prisma
Datasource "db": SQLite database

Error: Prisma schema validation - (get-config wasm)
Error code: P1012
error: Error validating datasource `db`: the URL must start with the protocol `file:`.
  -->  schema.prisma:7
   |
 6 |   provider = "sqlite"
 7 |   url      = env("DATABASE_URL")
   |

Validation Error Count: 1
[Context: getConfig]

Prisma CLI Version : 4.16.0

**Comment by daniserrano7** [comment]
You need to set the DATABASE_URL environmental variable in order to create the database. There is an example in the .sample.env file, so you only need to create an .env file with the required values and then run the prisma command. I already updated the readme file, thank you!
