### ISSUE TITLE
Will image resources be banned

### ISSUE THREAD

**Issue by cairongquan** [daniserrano7/jira-clone#2]
I saw that your code used random online image resources, and I was wondering if these resources would be intercepted across domains in the future.
```
export const getRandomProjectImage = (): string => {
  const randomNumber = getRandomNumberBetweenRange(0, 26);
  const formattedNumber = randomNumber.toString().padStart(2, "0");
  return `https://admin.atlassian.net/rest/api/2/universal_avatar/view/type/project/avatar/104${formattedNumber}?size=xxlarge`;
};

const getRandomNumberBetweenRange = (min: number, max: number): number => {
  return Math.floor(Math.random() * (max - min + 1) + min);
};

```

**Comment by cairongquan** [comment]
Alternatively, I can use a script to download and save these images locally

**Comment by cairongquan** [comment]
have u any idea?

**Comment by daniserrano7** [comment]
You are right. I'll download and store all images locally to prevent banning (and reduce load time). I'll fix it.

**Comment by daniserrano7** [comment]
Solved with https://github.com/daniserrano7/jira-clone/pull/3
